In [2]:
import numpy as np
from scipy import sparse
import pandas as pd

In [8]:
cache_path = "Data/gnn/cache_helgeland.npz"
npz = np.load(cache_path, allow_pickle=True)
X = npz["X"]; y = npz["y"]; ids = npz["ids"]
A_norm = sparse.csr_matrix(
            (npz["A_data"], npz["A_indices"], npz["A_indptr"]),
            shape=npz["A_shape"]
        )
print(X.shape, y.shape, ids.shape, A_norm.shape)

(5717, 65344) (5717,) (5717,) (5717, 5717)

In [3]:
X

array([[0., 1., 0., ..., 2., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 2., 1., ..., 0., 0., 1.],
       ...,
       [0., 2., 0., ..., 0., 0., 2.],
       [0., 2., 0., ..., 0., 0., 2.],
       [0., 0., 0., ..., 2., 0., 0.]], dtype=float32)

In [4]:
y

array([ 3.8494434 ,  1.7991    ,  0.50056416, ...,  0.75904787,
       -0.48954433,  0.08736372], dtype=float32)

In [5]:
ids

array(['8L19505', '8L19506', '8L19540', ..., '8981971', '8981972',
       '8L49911'], dtype=object)

In [13]:
a_df = pd.DataFrame(A_norm.toarray())
a_df

,0,1,2,3,4,5,6,7,8,9,...,5707,5708,5709,5710,5711,5712,5713,5714,5715,5716
0,0.200000,0.223607,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.000000,0.000000,0.00,0.0,0.0
1,0.223607,0.250000,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.000000,0.000000,0.00,0.0,0.0
2,0.000000,0.000000,0.25,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.25,0.0,0.000000,0.000000,0.00,0.0,0.0
3,0.000000,0.000000,0.00,0.25,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.000000,0.000000,0.00,0.0,0.0
4,0.000000,0.000000,0.00,0.00,0.25,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.000000,0.000000,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5712,0.000000,0.000000,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.250000,0.204124,0.00,0.0,0.0
5713,0.000000,0.000000,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.204124,0.166667,0.00,0.0,0.0
5714,0.000000,0.000000,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.000000,0.000000,0.25,0.0,0.0
5715,0.000000,0.000000,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.000000,0.000000,0.00,0.2,0.0
5716,0.000000,0.000000,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.000000,0.000000,0.00,0.0,0.2

In [4]:
a = np.load("Data/gnn/snp_pheno_ALL.npz", allow_pickle=False)
a["snp"]

array([[0., 1., 0., ..., 2., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 2., 1., ..., 0., 0., 1.],
       ...,
       [0., 2., 0., ..., 0., 0., 2.],
       [0., 2., 0., ..., 0., 0., 2.],
       [0., 0., 0., ..., 2., 0., 0.]], dtype=float32)

In [5]:
a["body_mass"]

array([ 3.8494434 ,  1.7991    ,  0.50056416, ...,  0.75904787,
       -0.48954433,  0.08736372], dtype=float32)